### ISSUE TITLE
Installation Instructions

### ISSUE THREAD

**Issue by riskynacho** [risk-redux/control_freak#11]
Could / Would you add instructions on how to run this?

Thanks

**Comment by egyptiankarim** [comment]
@riskynacho sure thing! I'll update the README with some instructions. Quick summary:

1. Clone the code.
2. Install dependencies (Ruby and everything in the Gemfile).
3. Configure the `config/database.yml` file as appropriate.
4. Bootstrap the database tables (and seed with the `db/seeds.rb` file.
5. Launch the app (it's Rails).

I run the application locally when developing and testing, and deploy to Heroku for production.

**Comment by egyptiankarim** [comment]
5be2e6c7b36a7a92ccd6f230d1e976c124981586

@riskynacho let me know if this is sufficient. I'm happy to add more detail if you think it would be helpful. Just let me know.
